services:
  - type: web
    name: beauty-store-api
    env: node
    rootDir: apps/server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    plan: free
