services:
  - type: web
    name: beauty-store-api
    env: node
    rootDir: OneDrive/Desktop/project_Anti/apps/server
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npm start
    plan: free
